from pyplan.pyplan.diagram_shortcut.admin import *
from pyplan.pyplan.inputtemplate.admin import *
from pyplan.pyplan.common.email.admin import *
from pyplan.pyplan.usercompanies.admin import *
from pyplan.pyplan.users.admin import *
from pyplan.pyplan.user_company_preference.admin import *
from pyplan.pyplan.preference_module.admin import *
from pyplan.pyplan.preference.admin import *
from pyplan.pyplan.external_link.report.admin import *
from pyplan.pyplan.external_link.node.admin import *
from pyplan.pyplan.external_link.dashboard.admin import *
from pyplan.pyplan.external_link.admin import *
from pyplan.pyplan.companies.admin import *
from pyplan.pyplan.company_preference.admin import *
from pyplan.pyplan.department.admin import *
