title: Pyplan
description: Pyplan is a graphical Integrated Development Environment for creating and sharing Data Analytics Apps.
show_downloads: false
google_analytics: UA-154592986-1
theme: jekyll-theme-minimal
